name: Deploy to Aliyun

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Deploy to Aliyun Server
        run: |
          ssh -o StrictHostKeyChecking=no root@101.200.77.126 "
          if [ ! -d "/project/canvas" ]; then
          cd "/project" &&
          git clone git@github.com:Nicolas-zn/canvas.git
          fi &&
          cd /project/canvas &&
          git pull origin main &&
          # 执行你想要的部署命令，比如构建项目、重启服务等
          npm install &&
          npm run build:production &&
          if [ ! -d "/nico/nginx/html/canvas" ]; then
          mkdir -p /nico/nginx/html/canvas
          fi &&
          cp -r /project/canvas/dist/* /nico/nginx/html/canvas
          ## npm run build &&
          ## pm2 restart all
          "
